# Generated by Django 5.0.3 on 2024-04-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default="SOME STRING", max_length=20),
        ),
    ]
