# Generated by Django 5.0.3 on 2024-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(
                blank=True, default="SOME STRING", max_length=20, null=True
            ),
        ),
    ]
