# Generated by Django 5.0.3 on 2024-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=20),
        ),
    ]
